updated journal validation to show correct error string on validation…
reef-pi/reef-pi pull request #1315
Opened 2020-12-20 01:55 UTC by andysmitharng

… failure

Fixed journal validation

## Description

`Journal was using name for all three inputs when validating, updated description and unit to use proper validation error string"

## Related Issue

`If this PR fixes issues please list them for a better management of issues`

## Motivation and Context

`Describe the reason and the context of the enhancement`

## Screenshots (if appropriate):

2020-12-27 07:13 UTC, ranjib requested changes

2020-12-27 10:06 UTC, andysmitharng commented on front-end/src/journal/schema.js
> -    .required(i18next.t('journal:name_required')),
gotcha, I'll make the fix in my current branch and just delete this PR since it will be in the other journal UI work I'm finishing up.

2021-05-03 06:16 UTC, ranjib commented
@andysmitharng  checking in, still interested in this?

2021-05-08 23:57 UTC, ranjib commented
Closing due to inactivity. Please reopen this if you want to revive the effort

2021-05-08 23:57 UTC, closed without merging