Watchdog
reef-pi/reef-pi pull request #1317
Opened 2020-12-24 01:41 UTC by sabbene

While submitting a PR, please make sure the build is ok with Travis CI. If not fix it, and if you need help feel free to ask :blush: .

## Description

Adding support for systemd watchdog, so reef-pi service can be restarted if it hangs.  My golang isn't great, so please let me know if there are any issues.  The current health check is just to make sure that the address that is configured for reef-pi to listen on is accessible and acking to syn packets.

## Related Issue

NA

## Motivation and Context

Add support for systemd watchdog to allow systemd to restart reef-pi if it stops responding on the port/address it is listening on.

## Screenshots (if appropriate):

2020-12-27 07:41 UTC, ranjib commented
@sabbene Thank you for the PR
It will be awesome if you can isolate the Dockerfile changes and submit as separate PR, it will help others, and run on deprecated os right now. 

I think we should keep the main controller as it is, and run the watchdog go-routine as part of the health module.  We should make it optional (i.e. user should be able to opt-in /out watchdog functionality).  Let's not change the default unit file right now (since it's opt in).
Move the systemd specific logic on controller/utils/systemd (StartSDNotify()), and remove the tcp check. A simple tcp syn check does not provide much. The controller can run even if API (bad IP configuration) fails. Also, I am not sure how the tcp check will react to bad IP or 0.0.0.0. With all this in mind, i think the tcp check does not add much value than vanilla sd notify at a periodic intervals.

2020-12-27 07:49 UTC, ranjib requested changes
- Move systemd specific usage to controller/utils/systemd.go , as StartSDNotify()
- Make watchdog feature optional and under health subsystem
- Remove tcp based check.

2020-12-27 08:30 UTC, sabbene commented
Sure, I can make those changes.  Making the changes to the UI to make the watchdog stuff optional may take me a bit of time.  Don't know much react.  There probably needs to be some sort of popup if you enable the watchdog explaining how to modify the unit files, and restart the daemon?  But it does seem not super useful if there isn't some sort of health check, maybe there is some other health check that could be performed?.  I tested with 0.0.0.0 and the check is performed against localhost, there is a screenshot of tcpdump below.

![image](https://user-images.githubusercontent.com/11637137/103166771-3904f180-47da-11eb-890f-86ba47fc59cb.png)

2020-12-28 12:08 UTC, hectorespert commented
@sabbene Is this watchdog feature only for the reef-pi systemd service? Could it support [this watchdog daemon](https://github.com/reef-pi/reef-pi.github.io/pull/15/files)?

2020-12-28 18:59 UTC, sabbene commented
@hectorespert -- Is is a slightly different watchdog mechanism.  The watchdog in your link is for detecting system issues that require a reboot.  The systemd watchdog is for system daemons to check in with systemd regularly, and be restarted if there are any issues.  I supposed that the test/repair scripts for the system watchdog could be used to implement a similar feature, but that seems like a kludge.

2020-12-29 06:19 UTC, ranjib commented
@hectorespert the userland watchdog daemon predates systemd and is not required once systemd watchdog is in place for our use case at least

2020-12-29 10:01 UTC, hectorespert commented
> @hectorespert the userland watchdog daemon predates systemd and is not required once systemd watchdog is in place for our use case at least

Can Systemd watchdog protect from a block generated from other program or other block condition?

2021-05-03 06:17 UTC, ranjib commented
@sabbene checking in, still interested in this?

2021-05-08 23:57 UTC, ranjib commented
Closing due to inactivity. Please reopen if you want to revive this

2021-05-08 23:57 UTC, closed without merging